### ISSUE TITLE
Set as template repository?

### ISSUE THREAD

**Issue by apetro** [CoralineAda/lftm#3]
1. I think after the creation of this repo, GitHub added a ["Template repository" feature](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository)
2. This feels like a template repository. An intended use is to enable adopters to make a repository like this one and use it for their own productivity.
3. Many adopters will want to do so in a private-visability repository. Forking a non-template public repository results in a public repository. However, [making a repo from a template can make a private repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-repository-from-a-template#creating-a-repository-from-a-template). This is a key feature.
4. Therefore, tic the Template box in settings for this repo, and thereby ease adoption. :)

**Comment by CoralineAda** [comment]
Great idea! Done. 💯
